[build]
command = "npm run build:netlify"
publish = "dist"
functions = "netlify/functions"

# Development settings only - these don't affect production
[dev]
command = "npm run dev"
targetPort = 5173
port = 8888
autoLaunch = true

# Handle API requests through proxy in production
[[redirects]]
from = "/api/*"
to = "https://spectra-api-server.onrender.com/api/:splat"
status = 200
force = true

# Handle client-side routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
