[build]
command = "npm run build"
publish = "dist"

[dev]
command = "npm run dev"
targetPort = 5173
port = 8888
autoLaunch = true

[[redirects]]
from = "/api/*"
to = "http://localhost:3001/api/:splat"
status = 200
force = true
