[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect API requests to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirect all other routes to the index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
status = 200

# Handle client-side routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
